name: longitude_and_latitude_in_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-174.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
