name: longitude_and_latitude_in_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-174.0.dev <4.0.0'

dependencies:
  cron: ^0.5.1
  flutter:
    sdk: flutter
  flutter_sms: ^2.3.3
  geolocator: ^10.0.1
  sms_receiver: ^0.4.2
  telephony: ^0.2.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
